# Generated by Django 4.2.10 on 2024-03-17 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название рекламной кампании')),
                ('promotion_channel', models.SmallIntegerField(choices=[(1, 'Социальные сети'), (2, 'Собственный сайт'), (3, 'Другие каналы в интернет'), (4, 'Наружная реклама'), (5, 'Журналы и газеты'), (6, 'Телевидение'), (7, 'Радио'), (8, 'Другие варианты')], default=3, verbose_name='Канал продвижения рекламной кампании')),
                ('description', models.TextField(verbose_name='Описание рекламной кампании')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Бюджет рекламной кампании')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Услуга рекламной кампании')),
            ],
            options={
                'verbose_name': 'рекламная компания',
                'verbose_name_plural': 'рекламные компании',
            },
        ),
    ]
