# Generated by Django 4.2.10 on 2024-03-17 16:21

import crm.leads.service
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, validators=[crm.leads.service.UnicodeNameValidator()], verbose_name='Имя потенциального клиента')),
                ('last_name', models.CharField(max_length=150, validators=[crm.leads.service.UnicodeNameValidator()], verbose_name='Фамилия потенциального клиента')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта потенциального клиента')),
                ('phone', models.CharField(max_length=14, validators=[crm.leads.service.UnicodeNumberValidator()], verbose_name='Телефон потенциального клиента')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('to_active', models.BooleanField(default=False, verbose_name='Перевод в активные')),
                ('ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.ads', verbose_name='Рекламная кампания')),
            ],
            options={
                'verbose_name': 'потенциальный клиент',
                'verbose_name_plural': 'потенциальные клиенты',
                'permissions': [('can_transfer_to_active', 'Can transfer to active')],
            },
        ),
    ]
